### ISSUE TITLE
Update cpptools does nothing

### ISSUE THREAD

**Issue by hongxinliu** [maddouri/vscode-cmake-tools-helper#12]
"CMake: Update cpptools" does nothing in a CMake based project. ("CMake: Configure" works successfully)

On both macOS and Ubuntu: 
vscode: 1.23.1
cpptools: 0.17.4
cmake-tools: 0.11.1
cmake-tools-helper: 0.2.1

**Comment by atship** [comment]
same problem on window7 x64. @maddouri

**Comment by MB3hel** [comment]
Same issue on Windows 10 x64 with VSCode 1.23.1 and 1.22.2

**Comment by remigastaldi** [comment]
Same problem, Archlinux x64 VSCode 1.24
this is the console log :
[Extension Host] TypeError: Cannot read property 'then' of undefined
	at CMakeToolsHelper.activeCMakeConfigName (/home/gastal_r/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/state.js:36:48)
	at CMakeToolsHelper.updateCppTools (/home/gastal_r/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/state.js:66:14)
	at CMakeToolsHelper.update_cpptools (/home/gastal_r/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/state.js:106:18)
	at context.subscriptions.push.vscode.commands.registerCommand._ (/home/gastal_r/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/extension.js:15:93)
	at e._executeContributedCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:674:613)
	at e.$executeContributedCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:675:6)
	at e._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:636:832)
	at e._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:636:550)
	at e._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:635:631)
	at e._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:635:400)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:634:315
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:637:395
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:95:432
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:764)
	at Socket.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)****

**Comment by lal12** [comment]
Linux Mint 18.2, I got the same vscode version, the same problem and the same log output as @remigastaldi
