### ISSUE TITLE
Extension fails to activate

### ISSUE THREAD

**Issue by Gnurfos** [maddouri/vscode-cmake-tools-helper#13]
I'm seeing this error in the console:

> [Extension Host] Activating extension 'maddouri.cmake-tools-helper' failed: Cannot read property 'reconfigured' of undefined.

It looks different from #12 despite the similar error: my symptoms are all command failing with for example:

> command 'cmake.update_cpptools' not found

It could come from some changes in the way cmake-tools expose their API, but I found nothing recent and obvious, after a very quick look.

Tested with cmaketools version 1.1.1 and cmaketools helper 0.2.1

**Comment by metorm** [comment]
I am faced with this problem, too.

```
vs-code: 1.32.2

Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.30-1-MANJARO

CMake Tools
id: vector-of-bool.cmake-tools
version : 1.1.3

CMake Tools Helper
id: maddouri.cmake-tools-helper
version: 0.2.1

```

When I execute the `CMake: Update cpptools` command, a pop-up message says `command 'cmake.update_cpptools' not found`

**Comment by 7kbird** [comment]
same here.

`cmake-tools-helper` never generate any `c_cpp_properties.json`, so I try reinstall this extension.

When try to install `cmake-tools-helper`, the developer console said:

> workbench.main.js:238 [Extension Host] Activating extension `maddouri.cmake-tools-helper` failed:  Cannot read property 'reconfigured' of undefined

```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'reconfigured' of undefined
	at new CMakeToolsHelper (/Users/kevin/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/state.js:13:33)
	at activate (/Users/kevin/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/out/src/extension.js:10:28)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:738:936)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:738:625)
	at define._doActivateExtension.Promise.all.then.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:737:635)
```

Env:
- OS: macOS Mojave v10.14.5
- VSCode: Version 1.35.0(553cfb2c2205db5f15f3ee8395bbd5cf066d357d)
- vector-of-bool.cmake-tools: 1.1.3
- maddouri.cmake-tools-helper: 0.2.1
- cmake version 3.14.5
